# Generated by Django 4.1.5 on 2023-01-10 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("perfil", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="name",
        ),
        migrations.AddField(
            model_name="user",
            name="nome",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
