# Generated by Django 4.1.5 on 2023-01-10 22:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("recomendacao", "0001_initial"),
        ("perfil", "0002_remove_user_name_user_nome"),
    ]

    operations = [
        migrations.AddField(
            model_name="perfil",
            name="guia",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="recomendacao.guiadehidratacaopessoal",
            ),
        ),
    ]
