# Generated by Django 4.1.5 on 2023-01-11 09:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("perfil", "0003_perfil_guia"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="perfil",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="perfil.perfil",
            ),
        ),
    ]
