# Generated by Django 4.1.5 on 2023-01-10 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="GuiaDeHidratacaoPessoal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("recomendacao", models.DecimalField(decimal_places=2, max_digits=6)),
                ("meta", models.DecimalField(decimal_places=2, max_digits=6)),
            ],
        ),
    ]
