# Generated by Django 4.1.5 on 2023-01-13 20:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Perfil",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("username", models.CharField(max_length=50, unique=True)),
                ("nome", models.CharField(max_length=50)),
                ("peso", models.DecimalField(decimal_places=2, max_digits=5)),
                ("meta", models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name="ConsumoDia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("data", models.DateField()),
                ("is_meta_atingida", models.BooleanField(default=False)),
                ("consumo", models.PositiveIntegerField()),
                (
                    "perfil",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="consumo.perfil"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Consumo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("volume", models.PositiveIntegerField()),
                ("data", models.DateTimeField(auto_now_add=True)),
                (
                    "consumoDia",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="consumos",
                        to="consumo.consumodia",
                    ),
                ),
            ],
        ),
    ]
