# Generated by Django 4.1.5 on 2023-01-13 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("consumo", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="consumodia",
            name="meta",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
