# Generated by Django 4.1.5 on 2023-01-12 21:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("consumo", "0001_initial"),
        ("perfil", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="consumodia",
            name="perfil",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="perfil.perfil"
            ),
        ),
        migrations.AddField(
            model_name="consumo",
            name="consumoDia",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="consumos",
                to="consumo.consumodia",
            ),
        ),
    ]
