# Generated by Django 4.1.5 on 2023-01-12 23:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("consumo", "0002_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Copo",
        ),
    ]
